from typing import Dict, List
from app.models.billing import Plan, PlanFeature

PLAN_CONFIG: Dict[str, dict] = {
    "free": {
        "name": "Free",
        "description": "Perfect for personal projects and trying out GhostLink",
        "price_monthly": 0,
        "price_yearly": 0,
        "currency": "usd",
        "limits": {
            "sites": 1,
            "site_scans_per_month": 5,
            "api_calls_per_month": 100,
            "team_members": 1,
            "analytics_retention_days": 30,
            "reports_export": False,
            "custom_branding": False,
            "priority_support": False,
            "webhook_endpoints": 0,
            "api_access": False,
        },
        "features": [
            PlanFeature(code="ai_analysis", name="AI Site Analysis", description="AI-powered site analysis and optimization suggestions", included=True),
            PlanFeature(code="json_ld", name="JSON-LD Generation", description="Automatic structured data generation", included=True),
            PlanFeature(code="llms_txt", name="LLMs.txt Generation", description="AI-friendly site summary generation", included=True),
            PlanFeature(code="basic_analytics", name="Basic Analytics", description="Track AI bot visits to your site", included=True),
            PlanFeature(code="tracking_script", name="Tracking Script", description="JavaScript snippet for your website", included=True),
            PlanFeature(code="seo_audit", name="SEO Audit", description="Basic SEO analysis and recommendations", included=True),
        ],
        "is_popular": False,
        "is_enterprise": False,
    },
    "starter": {
        "name": "Starter",
        "description": "For professionals and small businesses getting serious about AI optimization",
        "price_monthly": 1900,
        "price_yearly": 1599,
        "currency": "usd",
        "limits": {
            "sites": 3,
            "site_scans_per_month": 50,
            "api_calls_per_month": 1000,
            "team_members": 2,
            "analytics_retention_days": 90,
            "reports_export": True,
            "custom_branding": False,
            "priority_support": False,
            "webhook_endpoints": 1,
            "api_access": True,
        },
        "features": [
            PlanFeature(code="ai_analysis", name="AI Site Analysis", description="AI-powered site analysis and optimization suggestions", included=True),
            PlanFeature(code="json_ld", name="JSON-LD Generation", description="Automatic structured data generation", included=True),
            PlanFeature(code="llms_txt", name="LLMs.txt Generation", description="AI-friendly site summary generation", included=True),
            PlanFeature(code="advanced_analytics", name="Advanced Analytics", description="Detailed analytics with historical data", included=True),
            PlanFeature(code="tracking_script", name="Tracking Script", description="JavaScript snippet for your website", included=True),
            PlanFeature(code="seo_audit", name="SEO Audit", description="Comprehensive SEO analysis and recommendations", included=True),
            PlanFeature(code="scheduled_scans", name="Scheduled Scans", description="Automatic weekly site rescans", included=True),
            PlanFeature(code="api_access", name="API Access", description="Programmatic access to GhostLink API", included=True),
            PlanFeature(code="export_reports", name="Export Reports", description="PDF and CSV report exports", included=True),
        ],
        "is_popular": False,
        "is_enterprise": False,
    },
    "pro": {
        "name": "Pro",
        "description": "For growing businesses and agencies managing multiple sites",
        "price_monthly": 4900,
        "price_yearly": 3999,
        "currency": "usd",
        "limits": {
            "sites": 10,
            "site_scans_per_month": 500,
            "api_calls_per_month": 10000,
            "team_members": 5,
            "analytics_retention_days": 365,
            "reports_export": True,
            "custom_branding": True,
            "priority_support": True,
            "webhook_endpoints": 5,
            "api_access": True,
        },
        "features": [
            PlanFeature(code="ai_analysis", name="AI Site Analysis", description="AI-powered site analysis and optimization suggestions", included=True),
            PlanFeature(code="json_ld", name="JSON-LD Generation", description="Automatic structured data generation", included=True),
            PlanFeature(code="llms_txt", name="LLMs.txt Generation", description="AI-friendly site summary generation", included=True),
            PlanFeature(code="advanced_analytics", name="Advanced Analytics", description="Detailed analytics with historical data", included=True),
            PlanFeature(code="tracking_script", name="Tracking Script", description="JavaScript snippet for your website", included=True),
            PlanFeature(code="seo_audit", name="SEO Audit", description="Comprehensive SEO analysis and recommendations", included=True),
            PlanFeature(code="scheduled_scans", name="Scheduled Scans", description="Automatic daily site rescans", included=True),
            PlanFeature(code="api_access", name="API Access", description="Programmatic access to GhostLink API", included=True),
            PlanFeature(code="export_reports", name="Export Reports", description="PDF and CSV report exports", included=True),
            PlanFeature(code="custom_branding", name="Custom Branding", description="Remove GhostLink branding from reports", included=True),
            PlanFeature(code="priority_support", name="Priority Support", description="Priority email support with 24h response", included=True),
            PlanFeature(code="team_collaboration", name="Team Collaboration", description="Invite team members to collaborate", included=True),
            PlanFeature(code="webhooks", name="Webhooks", description="Real-time event notifications", included=True),
        ],
        "is_popular": True,
        "is_enterprise": False,
    },
    "business": {
        "name": "Business",
        "description": "For large organizations with advanced needs",
        "price_monthly": 9900,
        "price_yearly": 7999,
        "currency": "usd",
        "limits": {
            "sites": 50,
            "site_scans_per_month": 2000,
            "api_calls_per_month": 100000,
            "team_members": 20,
            "analytics_retention_days": 730,
            "reports_export": True,
            "custom_branding": True,
            "priority_support": True,
            "webhook_endpoints": 20,
            "api_access": True,
            "dedicated_support": True,
            "sla_guarantee": True,
        },
        "features": [
            PlanFeature(code="ai_analysis", name="AI Site Analysis", description="AI-powered site analysis and optimization suggestions", included=True),
            PlanFeature(code="json_ld", name="JSON-LD Generation", description="Automatic structured data generation", included=True),
            PlanFeature(code="llms_txt", name="LLMs.txt Generation", description="AI-friendly site summary generation", included=True),
            PlanFeature(code="advanced_analytics", name="Advanced Analytics", description="Detailed analytics with historical data", included=True),
            PlanFeature(code="tracking_script", name="Tracking Script", description="JavaScript snippet for your website", included=True),
            PlanFeature(code="seo_audit", name="SEO Audit", description="Comprehensive SEO analysis and recommendations", included=True),
            PlanFeature(code="scheduled_scans", name="Scheduled Scans", description="Automatic hourly site rescans", included=True),
            PlanFeature(code="api_access", name="API Access", description="Programmatic access to GhostLink API", included=True),
            PlanFeature(code="export_reports", name="Export Reports", description="PDF and CSV report exports", included=True),
            PlanFeature(code="custom_branding", name="Custom Branding", description="Remove GhostLink branding from reports", included=True),
            PlanFeature(code="priority_support", name="Priority Support", description="Priority email support with 4h response", included=True),
            PlanFeature(code="team_collaboration", name="Team Collaboration", description="Invite team members to collaborate", included=True),
            PlanFeature(code="webhooks", name="Webhooks", description="Real-time event notifications", included=True),
            PlanFeature(code="white_label", name="White-label Reports", description="Custom branded client reports", included=True),
            PlanFeature(code="audit_log", name="Audit Log", description="Complete activity audit trail", included=True),
        ],
        "is_popular": False,
        "is_enterprise": False,
    },
    "enterprise": {
        "name": "Enterprise",
        "description": "Custom solutions for large enterprises with specific requirements",
        "price_monthly": 0,
        "price_yearly": 0,
        "currency": "usd",
        "limits": {
            "sites": -1,
            "site_scans_per_month": -1,
            "api_calls_per_month": -1,
            "team_members": -1,
            "analytics_retention_days": -1,
            "reports_export": True,
            "custom_branding": True,
            "priority_support": True,
            "webhook_endpoints": -1,
            "api_access": True,
            "dedicated_support": True,
            "sla_guarantee": True,
            "custom_contract": True,
        },
        "features": [
            PlanFeature(code="everything_in_business", name="Everything in Business", description="All Business plan features included", included=True),
            PlanFeature(code="custom_contract", name="Custom Contract", description="Flexible billing and contract terms", included=True),
            PlanFeature(code="dedicated_manager", name="Dedicated Account Manager", description="Your personal GhostLink specialist", included=True),
            PlanFeature(code="custom_development", name="Custom Development", description="Feature development on request", included=True),
            PlanFeature(code="sla_guarantee", name="SLA Guarantee", description="99.9% uptime guarantee with penalties", included=True),
            PlanFeature(code="sso", name="SSO/SAML", description="Single sign-on integration", included=True),
            PlanFeature(code="security_review", name="Security Review", description="Annual security assessment", included=True),
        ],
        "is_popular": False,
        "is_enterprise": True,
    },
}

def get_plan(plan_code: str) -> Plan:
    config = PLAN_CONFIG.get(plan_code, PLAN_CONFIG["free"])
    return Plan(
        code=plan_code,
        name=config["name"],
        description=config["description"],
        price_monthly=config["price_monthly"],
        price_yearly=config["price_yearly"],
        currency=config["currency"],
        features=config["features"],
        limits=config["limits"],
        is_popular=config.get("is_popular", False),
        is_enterprise=config.get("is_enterprise", False),
    )

def get_all_plans() -> List[Plan]:
    return [get_plan(code) for code in PLAN_CONFIG.keys()]

def get_plan_limit(plan_code: str, limit_name: str) -> int:
    plan_config = PLAN_CONFIG.get(plan_code, PLAN_CONFIG["free"])
    return plan_config["limits"].get(limit_name, 0)

def can_use_feature(plan_code: str, feature_code: str) -> bool:
    plan_config = PLAN_CONFIG.get(plan_code, PLAN_CONFIG["free"])
    for feature in plan_config["features"]:
        if feature.code == feature_code:
            return feature.included
    return False
